; Generated by MiniCompiler (Sprint 5)
; NASM syntax for x86-64

BITS 64

section .text
global main

; Function: main
global main
main:
    ; Prologue
    push rbp
    mov rbp, rsp
    sub rsp, 32

entry_1:
    mov qword [rbp-8], 10 ; init x
    mov qword [rbp-16], 20 ; init y
    mov rax, qword [rbp-8]
    add rax, qword [rbp-16]
    mov qword [rbp-24], rax
    mov rax, qword [rbp-24]
    mov qword [rbp-32], rax ; init z
    mov rax, qword [rbp-32] ; return value
    ; Epilogue
    mov rsp, rbp
    pop rbp
    ret




; Runtime functions
extern print_int
extern print_string
extern exit
