# src/codegen/x86_generator.py
"""x86-64 assembly code generator.
Sprint 5 requirements: ASM-1, ASM-2, ASM-3, ASM-4, ASM-5
"""

from typing import Dict, List, Optional
from ..ir import ProgramIR, FunctionIR, BasicBlock, Instruction, Opcode, Operand, Temp, Var, Const, Label


class X86Generator:
    """Generate x86-64 assembly from IR."""

    def __init__(self, use_nasm: bool = True):
        self.use_nasm = use_nasm
        self.assembly: List[str] = []
        self.current_function: Optional[FunctionIR] = None
        self.label_counter = 0
        self.string_counter = 0
        self.string_literals: Dict[str, str] = {}

        # Stack frame info
        self.stack_size = 0
        self.local_offset = 0

        # Variable to stack offset mapping
        self.var_offsets: Dict[str, int] = {}

    def generate(self, program_ir: ProgramIR) -> str:
        """Generate assembly for entire program."""
        self.assembly = []

        # Add header
        self._add_header()

        # Generate data section for string literals
        self._generate_data_section()

        # Generate text section
        self.assembly.append("section .text")
        self.assembly.append("global main")
        self.assembly.append("")

        # Generate each function
        for func in program_ir.functions:
            self._generate_function(func)

        # Add runtime stubs
        self._generate_runtime_stubs()

        return "\n".join(self.assembly)

    def _add_header(self):
        """Add assembly header."""
        if self.use_nasm:
            self.assembly.append("; Generated by MiniCompiler (Sprint 5)")
            self.assembly.append("; NASM syntax for x86-64")
            self.assembly.append("")
            self.assembly.append("BITS 64")
            self.assembly.append("")

    def _generate_data_section(self):
        """Generate data section for string literals."""
        if self.string_literals:
            self.assembly.append("section .data")
            for value, label in self.string_literals.items():
                escaped = value.replace('\\', '\\\\').replace('"', '\\"')
                self.assembly.append(f'{label}: db "{escaped}", 0')
            self.assembly.append("")

    def _generate_function(self, func: FunctionIR):
        """Generate assembly for a function."""
        self.current_function = func
        self.var_offsets = {}
        self.local_offset = -8

        # Calculate stack frame size
        self._calculate_stack_frame(func)

        # Function label
        self.assembly.append(f"; Function: {func.name}")
        self.assembly.append(f"global {func.name}")
        self.assembly.append(f"{func.name}:")

        # Function prologue
        self._generate_prologue()

        # Generate each basic block
        for block in func.blocks:
            self._generate_basic_block(block)

        self.assembly.append("")

    def _calculate_stack_frame(self, func: FunctionIR):
        """Calculate total stack frame size needed."""
        local_count = len(func.var_mapping)
        self.stack_size = local_count * 8
        self.stack_size = (self.stack_size + 15) & ~15

    def _generate_prologue(self):
        """Generate function prologue."""
        self.assembly.append("    ; Prologue")
        self.assembly.append("    push rbp")
        self.assembly.append("    mov rbp, rsp")

        if self.stack_size > 0:
            self.assembly.append(f"    sub rsp, {self.stack_size}")
        self.assembly.append("")

    def _generate_epilogue(self):
        """Generate function epilogue."""
        self.assembly.append("    ; Epilogue")
        if self.stack_size > 0:
            self.assembly.append("    mov rsp, rbp")
        self.assembly.append("    pop rbp")
        self.assembly.append("    ret")
        self.assembly.append("")

    def _generate_basic_block(self, block: BasicBlock):
        """Generate a basic block."""
        self.assembly.append(f"{block.label.name}:")

        for inst in block.instructions:
            self._generate_instruction(inst)

        self.assembly.append("")

    def _generate_instruction(self, inst: Instruction):
        """Generate assembly for a single IR instruction."""
        comment = f" ; {inst.comment}" if inst.comment else ""

        if inst.opcode == Opcode.MOVE:
            dest = self._operand_to_asm(inst.dest, is_dest=True)
            src = self._operand_to_asm(inst.args[0] if inst.args else None)

            # Check if moving from memory to memory
            if 'qword [' in src and 'qword [' in dest:
                self.assembly.append(f"    mov rax, {src}")
                self.assembly.append(f"    mov {dest}, rax{comment}")
            else:
                self.assembly.append(f"    mov {dest}, {src}{comment}")

        elif inst.opcode == Opcode.ADD:
            dest = self._operand_to_asm(inst.dest, is_dest=True)
            left = self._operand_to_asm(inst.args[0])
            right = self._operand_to_asm(inst.args[1])

            # Load left operand into rax
            self.assembly.append(f"    mov rax, {left}")
            # Add right operand
            if 'qword [' in right:
                self.assembly.append(f"    add rax, {right}")
            else:
                self.assembly.append(f"    add rax, {right}")
            # Store result in destination
            self.assembly.append(f"    mov {dest}, rax{comment}")

        elif inst.opcode == Opcode.SUB:
            dest = self._operand_to_asm(inst.dest, is_dest=True)
            left = self._operand_to_asm(inst.args[0])
            right = self._operand_to_asm(inst.args[1])

            self.assembly.append(f"    mov rax, {left}")
            if 'qword [' in right:
                self.assembly.append(f"    sub rax, {right}")
            else:
                self.assembly.append(f"    sub rax, {right}")
            self.assembly.append(f"    mov {dest}, rax{comment}")

        elif inst.opcode == Opcode.MUL:
            dest = self._operand_to_asm(inst.dest, is_dest=True)
            left = self._operand_to_asm(inst.args[0])
            right = self._operand_to_asm(inst.args[1])

            self.assembly.append(f"    mov rax, {left}")
            if 'qword [' in right:
                self.assembly.append(f"    imul rax, {right}")
            else:
                self.assembly.append(f"    imul rax, {right}")
            self.assembly.append(f"    mov {dest}, rax{comment}")

        elif inst.opcode == Opcode.RETURN:
            if inst.args:
                val = self._operand_to_asm(inst.args[0])
                self.assembly.append(f"    mov rax, {val}{comment}")
            self._generate_epilogue()

        elif inst.opcode == Opcode.JUMP:
            target = inst.args[0] if inst.args else None
            self.assembly.append(f"    jmp {target}{comment}")

        elif inst.opcode == Opcode.JUMP_IF:
            cond = self._operand_to_asm(inst.args[0])
            target = inst.args[1]
            self.assembly.append(f"    cmp {cond}, 0")
            self.assembly.append(f"    jne {target}{comment}")

        elif inst.opcode == Opcode.CALL:
            func_name = self._operand_to_asm(inst.args[0])
            self.assembly.append(f"    call {func_name}{comment}")
            if inst.dest:
                self.assembly.append(f"    mov {self._operand_to_asm(inst.dest, is_dest=True)}, rax")

        elif inst.opcode in (Opcode.CMP_LT, Opcode.CMP_GT, Opcode.CMP_LE, Opcode.CMP_GE, Opcode.CMP_EQ, Opcode.CMP_NE):
            left = self._operand_to_asm(inst.args[0])
            right = self._operand_to_asm(inst.args[1])
            dest = self._operand_to_asm(inst.dest, is_dest=True)

            # Map opcode to set instruction
            set_map = {
                Opcode.CMP_LT: "setl",
                Opcode.CMP_GT: "setg",
                Opcode.CMP_LE: "setle",
                Opcode.CMP_GE: "setge",
                Opcode.CMP_EQ: "sete",
                Opcode.CMP_NE: "setne",
            }
            set_inst = set_map.get(inst.opcode, "sete")

            self.assembly.append(f"    cmp {left}, {right}")
            self.assembly.append(f"    xor eax, eax")
            self.assembly.append(f"    {set_inst} al")
            self.assembly.append(f"    mov {dest}, eax")

        else:
            self.assembly.append(f"    ; Unhandled: {inst.opcode.value}{comment}")

    def _operand_to_asm(self, operand: Optional[Operand], is_dest: bool = False) -> str:
        """Convert IR operand to x86-64 assembly."""
        if operand is None:
            return "0"

        if isinstance(operand, Const):
            if isinstance(operand.value, bool):
                return "1" if operand.value else "0"
            return str(operand.value)

        if isinstance(operand, Temp):
            if operand.name not in self.var_offsets:
                self.var_offsets[operand.name] = self.local_offset
                self.local_offset -= 8
            offset = self.var_offsets[operand.name]
            return f"qword [rbp{offset:+d}]"

        if isinstance(operand, Var):
            if self.current_function and operand.name in self.current_function.var_mapping:
                temp = self.current_function.var_mapping[operand.name]
                return self._operand_to_asm(temp)
            return operand.name

        if isinstance(operand, Label):
            return operand.name

        return str(operand)

    def _generate_runtime_stubs(self):
        """Generate runtime stubs."""
        self.assembly.append("")
        self.assembly.append("; Runtime functions")
        self.assembly.append("extern print_int")
        self.assembly.append("extern print_string")
        self.assembly.append("extern exit")
        self.assembly.append("")

    def add_string_literal(self, value: str) -> str:
        """Add a string literal."""
        if value not in self.string_literals:
            label = f".L.str{self.string_counter}"
            self.string_literals[value] = label
            self.string_counter += 1
        return self.string_literals[value]